# Netlify configuration for Vite + React SPA
[build]
  command = "npm run build"
  publish = "dist"

# Ensure SPA routes work by always serving index.html
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Client-side routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
